apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-fiftyone-testing"
spec:
  title: "FiftyOne Testing"
  description: "Testing of FiftyOne Python API."
  publish:
    image: "$(image_repository)/lab-fiftyone-testing-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/lab-fiftyone-testing-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
    ingresses:
    - name: fiftyone
      port: 5151
